// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinNativeTemplate.iOS
{
	public partial class EmployeeCell : UITableViewCell
	{
		public EmployeeCell (IntPtr handle) : base (handle)
		{
		}

        public void UpdateCell(Employee employee)
        {
            lblName.Text = employee.Name;
            lblNumber.Text = employee.Phone;
          

        }
	}
}
