// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace XamarinNativeTemplate.iOS
{
	public partial class FormViewController : UIViewController
	{
        MainViewModel MainVm
        {
            get
            {
                return AppDelegate.Locator.MainVm;
            }
        }
		public FormViewController (IntPtr handle) : base (handle)
		{
		}

        partial void AddNewEmployee(UIButton sender)
        {
            
            MainVm.AddEmployee(txtName.Text, txtNumber.Text, txtEmailId.Text, txtDOB.Text);
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


        }
	}
}
